package names

//模块名

const USER = "user"
const USERGROUP = "usergroup"
const MODULE = "module"
const LOG = "log"
const POSTTYPE = "posttype"
const POST = "post"
const PHOTO = "photo"
const ALBUM = "album"
const CONFIG = "config"
const ADS = "ads"
const ADSPOS = "adspos"
const SHOP_BRAND = "shopbrand"
const SHOP_ITEM = "shopitem"
const SHOP_ITEMTYPE = "shopitemtype"
const SHOP_NOTICE = "shopnotice"
const SHOP_TAG = "shoptag"
const SHOP_ORDER = "shoporder"
const EXPORT_TASK = "exporttask"
const EXPORT = "export"
const DATABASE = "database"
const PAYCODE = "paycode"
const LOGISTICS = "logistics"
const LOGISTICS_TASK = "logisticstask"
